Create abstract class Person, class Seller and class TestSeller for test
cs-kmitl-2017/group7 pull request #6
Opened 2017-12-05 13:15 UTC by MeeSerCle

2017-12-05 13:44 UTC, champillon requested changes
Code สวยมาก ฝากชี้แจง/แก้นิดนึงครับ

2017-12-05 13:44 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Person.java
> +    private String email;
ใน spec ปี 2560 นั้น uriId กับ email เป็นอันเดียวกันครับ ดังนั้นเอา email ออก

2017-12-05 13:44 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Seller.java
> +        /*
ทำไม comment ครับ???

2017-12-05 14:46 UTC, MeeSerCle commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Person.java
> +    private String email;
โอเคครับ

2017-12-05 14:49 UTC, MeeSerCle commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Seller.java
> +        /*
ไว้กันงงครับ

2017-12-05 15:20 UTC, champillon approved these changes
LGTM ละ รออีกคนมา review นะ

2017-12-06 03:28 UTC, merged

2017-12-06 03:41 UTC, champillon commented
ตัดคะแนนดังนี้

1. design as components (0.75 คะแนน) => data structure ของ seller กับ buyer เหมือนกัน ทำไมไม่สร้าง class เป็น Trader หรือ Company แล้วค่อยสร้างเป็น instance ของ seller หรือ buyer

2. naming & convention (0.75 คะแนน) => ไม่ควรทิ้ง comment ไว้ใน branch ที่ใช้ร่วมกันคนอื่นครับ โดยเฉพาะ comment ที่เป็น code เพราะจะทำให้เราไม่รู้ว่า code ที่ comment ไปนั้นใช้ทำอะไร ควรจะมีอยู่ต่อหรือไม่ แล้วจะไม่มีใครกล้าลบครับ

3. technology leveraging (0.5 คะแนน) => มีการใช้ abstract class และมีการ override equal พร้อม test

4. git usage (0.75 คะแนน) => commit log ยังไม่แสดงว่าไฟล์นั้นเปลี่ยนแปลงยังไง ยังเป็นภาพรวมๆของทั้ง PR ซึ่งยังหยาบไป เพราะเวลาเราดู version history เราจะดูทีละไฟล์ครับ

เขียน code ดีแล้ว อยากให้ PR ต่อไป ใช้เทคนิคที่ยากขึ้นกว่านี้ครับ
@MeeSerCle