Features: Create Address, UniversalCommunication, TradeContactFactory and Mock
cs-kmitl-2017/group7 pull request #8
Opened 2017-12-07 13:00 UTC by MeeSerCle

2017-12-07 14:50 UTC, champillon requested changes
ถ้าจ้างมาทำงาน คิดเงินเดือนเท่าไหร่ครับ?

2017-12-07 14:50 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/UniversalCommunication.java
> +public class UniversalCommunication extends TradeContact{
ทำไม UniversalCommunication ต้อง extends TradeContact อีกรอบด้วยครับ

2017-12-07 15:53 UTC, MeeSerCle commented on src/main/java/th/ac/kmitl/science/comsci/example/models/UniversalCommunication.java
> +public class UniversalCommunication extends TradeContact{
เพื่อนำข้อมูลในส่วนที่เหมือนกันไว้ใน TradeContact และแยกคลาส UniversalCommunication ของผู้ซื้อผู้ขาย กับ ผู้รับ ครับ

2017-12-07 16:40 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/UniversalCommunication.java
> +public class UniversalCommunication extends TradeContact{
ทำไม ต้องแยก ผู้ขาย ผู้ซื้อหล่ะ ในเมื่อ data structure เหมือนกัน?

2017-12-07 16:42 UTC, MeeSerCle commented on src/main/java/th/ac/kmitl/science/comsci/example/models/UniversalCommunication.java
> +public class UniversalCommunication extends TradeContact{
ขายซื้ออันเดียวกันครับ

2017-12-07 16:43 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/UniversalCommunication.java
> +public class UniversalCommunication extends TradeContact{
ขายซื้ออันเดียวกัน นี่ยังไงนะครับ?

2017-12-07 16:50 UTC, MeeSerCle commented on src/main/java/th/ac/kmitl/science/comsci/example/models/UniversalCommunication.java
> +public class UniversalCommunication extends TradeContact{
ผู้ขายผู้ซื้อใช้ UniversalCommunication ผู้รับใช้ อีกคลาสนึงที่ extends จาก TradeContact อีกทีครับ

2017-12-07 17:04 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/UniversalCommunication.java
> +public class UniversalCommunication extends TradeContact{
ผู้ขาย และผู้ซื้อควรเป็น class หรือเป็น instance ครับ???

2017-12-07 17:09 UTC, MeeSerCle commented on src/main/java/th/ac/kmitl/science/comsci/example/models/UniversalCommunication.java
> +public class UniversalCommunication extends TradeContact{
เป็น instance ครับ

2017-12-08 06:01 UTC, MeeSerCle commented on src/main/java/th/ac/kmitl/science/comsci/example/models/UniversalCommunication.java
> +public class UniversalCommunication extends TradeContact{
data structure เหมือนกัน ผมยุบ TradeContact กับ UniversalCommunication เป็นอันเดียวกันนะครับ

2017-12-08 10:15 UTC, champillon approved these changes
LGTM

2017-12-08 10:15 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/UniversalCommunication.java
> +public class UniversalCommunication extends TradeContact{
แล้วทำไม class instance ของผู้ซื้อ/ผู้ขาย (Trader) ต้องมา extend UniversalCommunication ด้วย
จะบอกว่า ผู้ซื้อ/ผู้ขาย เป็นสายการขยาย class ของ UniversalCommunication หรอ?

แต่จริงๆที่เรามีปัญหาคือ UniversalCommunication ต้อง extends TradeContact ด้วย เราไม่เข้าใจ inheritance ในจุดนี้

เราว่า สายการ inheritance ของนายมันแปลกๆอ่ะ

2017-12-08 10:18 UTC, khemtat approved these changes

2017-12-08 10:37 UTC, merged

2017-12-08 11:02 UTC, MeeSerCle commented
คำถาม "ถ้าจ้างมาทำงาน คิดเงินเดือนเท่าไหร่ครับ?"
ขออนุญาตตอบใน inbox นะครับ

2017-12-08 11:08 UTC, champillon commented
@MeeSerCle add facebook พี่มาคุยกันโลด