Refactor mock class to Singleton, add attribute and add test case
cs-kmitl-2017/group7 pull request #9
Opened 2017-12-08 16:29 UTC by MeeSerCle

- UniversalCommunicationMock, AddressMock and TraderMock class: Rename method in mock class from get to generate and convert to sigleton.

- Person class: Add attribute address, universalCommunication and create constructor method.

- Trader class: Edit constructor by add id parameter and remove uriId parameter. Add super method in constructor.

- UniversalCommunication class: Edit constructor method from call method setUriId to assign attribute.

- TraderTest, UniversalCommunocationTest and AddressTest class:  change data receive from mock.

2017-12-08 17:56 UTC, champillon requested changes
ขอ spec ของ UniversalCommunication หน่อยครับ ว่าเป็น List ได้

2017-12-08 17:56 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Person.java
> +    private List<UniversalCommunication> universalCommunication;
ขอ spec หน่อยครับ ว่า UniversalCommunication เป็น list ได้

2017-12-08 18:06 UTC, MeeSerCle commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Person.java
> +    private List<UniversalCommunication> universalCommunication;
![image](https://user-images.githubusercontent.com/11521591/33778832-fe0dabf6-dc7c-11e7-9732-8d2d33c553e1.png)

ตรงรายละเอียดการติดต่อ 0..n

2017-12-09 03:09 UTC, champillon approved these changes
LGTM

แต่ PR นี้นายทำใหญ่ไปนะ จริงๆ แยกได้ 2 PR เลยมั้ง
1. ทำ Singleton สำหรับ Mock
2. เปลี่ยน UniversalCommunication เป็น List

รอบหน้า PR เล็กๆ จะดีกว่า

2017-12-09 12:38 UTC, MeeSerCle commented
PR นี้มีส่วนต้องแก้ไขอีกไหมครับ

2017-12-09 12:45 UTC, khemtat commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Trader.java
>          Trader other = (Trader) obj;
```java
Trader other = (Trader) obj;
```

ตั้งชื่อว่า `other` มันดูแปลก ๆ มั้ยครับ เปลี่ยนเป็น `trader` ไปเลยจะเหมาะกว่าไหมครับ

เพราะยังไงใน scope ของ `equals` method นี้เราก็ไม่มีการใช้ `trader` ตัวอื่นอยู่แล้ว

2017-12-09 12:46 UTC, khemtat commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Trader.java
>          Trader other = (Trader) obj;
```java
Trader other = (Trader) obj;
```

ตั้งชื่อว่า `other` มันดูแปลก ๆ มั้ยครับ เปลี่ยนเป็น `trader` ไปเลยจะเหมาะกว่าไหมครับ

เพราะยังไงใน scope ของ `equals` method นี้เราก็ไม่มีการใช้ `trader` ตัวอื่นอยู่แล้ว

2017-12-09 13:01 UTC, MeeSerCle commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Trader.java
>          Trader other = (Trader) obj;
โอเคครับ แก้ไขแล้วครับ

2017-12-09 13:01 UTC, khemtat approved these changes

2017-12-09 13:09 UTC, merged